### ISSUE TITLE
Jobseeker Introduction Page input changes

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#24]
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Enhancement

### Issue Description

- [x] Remove Current School / Graduated School
![{50CF693B-877A-408F-B763-A95F818C207B}](https://github.com/user-attachments/assets/3c6e8abf-7ae0-446b-8ff2-5a4e28a25fb0)
- [ ] Move Headlines to /create-profile/jobseeker/showcase page
![{63202953-6E85-4AED-8470-15E5186DE347}](https://github.com/user-attachments/assets/7ffc2c83-5107-4931-8971-d13414fa920d)
- [ ] Move Current position input and resume upload to /create-profile/jobseeker/work-experience
![{143B6C7D-E585-4FA9-B8F8-B971F4BC3774}](https://github.com/user-attachments/assets/48fb87ea-4c28-47be-86b5-85393d6dbcd9)
- [ ] modify work-experience api route to accept resume and current position
- [ ] remove work-experience, current school/graduated school and resume upload from introduction API route.
- [ ] removed Intro section from /create-profile/jobseeker/introduction

### URL of the Page

/create-profile/jobseeker/introduction

### Steps to Reproduce

N/A

### Recommended Priority Level

Medium

**Comment by rorosaurus** [comment]
I'm also noticing an issue when submitting this intro page. Not sure if would make sense to investigate as part of this issue or create a new one. @theGaryLarson @Gabe-Bryan 

```
Argument `zip` must not be null.
    at Tn (D:\CFA\frontend-cfa\node_modules\@prisma\client\runtime\library.js:115:6855)
    at In.handleRequestError (D:\CFA\frontend-cfa\node_modules\@prisma\client\runtime\library.js:122:6533)    
    at In.handleAndLogRequestError (D:\CFA\frontend-cfa\node_modules\@prisma\client\runtime\library.js:122:6211)
    at In.request (D:\CFA\frontend-cfa\node_modules\@prisma\client\runtime\library.js:122:5919)
    at async l (D:\CFA\frontend-cfa\node_modules\@prisma\client\runtime\library.js:127:11167)
    at async eval (webpack-internal:///(rsc)/./app/api/jobseekers/account/introduction/upsert/route.ts:24:26) 
    at async Proxy._transactionWithCallback (D:\CFA\frontend-cfa\node_modules\@prisma\client\runtime\library.js:127:9534)
    at async POST (webpack-internal:///(rsc)/./app/api/jobseekers/account/introduction/upsert/route.ts:22:24) 
    at async D:\CFA\frontend-cfa\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:53446 
    at async e_.execute (D:\CFA\frontend-cfa\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:44747)
    at async e_.handle (D:\CFA\frontend-cfa\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:54700)
    at async doRender (D:\CFA\frontend-cfa\node_modules\next\dist\server\base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (D:\CFA\frontend-cfa\node_modules\next\dist\server\base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (D:\CFA\frontend-cfa\node_modules\next\dist\server\base-server.js:1507:28)
    at async DevServer.renderPageComponent (D:\CFA\frontend-cfa\node_modules\next\dist\server\base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (D:\CFA\frontend-cfa\node_modules\next\dist\server\base-server.js:1962:32)
    at async DevServer.pipeImpl (D:\CFA\frontend-cfa\node_modules\next\dist\server\base-server.js:920:25)     
    at async NextNodeServer.handleCatchallRenderRequest (D:\CFA\frontend-cfa\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (D:\CFA\frontend-cfa\node_modules\next\dist\server\base-server.js:816:17)
    at async D:\CFA\frontend-cfa\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (D:\CFA\frontend-cfa\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (D:\CFA\frontend-cfa\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (D:\CFA\frontend-cfa\node_modules\next\dist\server\lib\router-server.js:174:21)     
    at async handleRequest (D:\CFA\frontend-cfa\node_modules\next\dist\server\lib\router-server.js:353:24)    
    at async requestHandlerImpl (D:\CFA\frontend-cfa\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (D:\CFA\frontend-cfa\node_modules\next\dist\server\lib\start-server.js:141:13) {
  clientVersion: '5.14.0'
}
 POST /api/jobseekers/account/introduction/upsert 500 in 5090ms
```
